export default {
    //<---* I. Customer Authentication * --->
    //User cantive
    CAN_ACTIVE: 'CAN_ACTIVE',
    CAN_ACTIVE_SUCCESS: 'CAN_ACTIVE_SUCCESS',
    CAN_ACTIVE_ERROR: 'CAN_ACTIVE_ERROR',
    //user login
    LOGIN_EMAIL_PASSWORD: 'LOGIN_EMAIL_PASSWORD',
    LOGIN_EMAIL_PASSWORD_SUCCESS: 'LOGIN_EMAIL_PASSWORD_SUCCESS',
    LOGIN_EMAIL_PASSWORD_ERROR: 'LOGIN_EMAIL_PASSWORD_ERROR',

    REGISTER_EMAIL_PASSWORD: 'REGISTER_EMAIL_PASSWORD',
    REGISTER_EMAIL_PASSWORD_SUCCESS: 'REGISTER_EMAIL_PASSWORD_SUCCESS',
    REGISTER_EMAIL_PASSWORD_ERROR: 'REGISTER_EMAIL_PASSWORD_ERROR',

    CREATE_USER: 'CREATE_USER',
    CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
    CREATE_USER_ERROR: 'CREATE_USER_ERROR',

    LOG_OUT: 'LOG_OUT',
    LOG_OUT_SUCCESS: 'LOG_OUT_SUCCESS',
    LOG_OUT_ERROR: 'LOG_OUT_ERROR',

    ON_FACEBOOK: 'ON_FACEBOOK',
    ON_FACEBOOK_SUCCESS: 'ON_FACEBOOK_SUCCESS',
    ON_FACEBOOK_ERROR: 'ON_FACEBOOK_ERROR',

    ON_GOOGLE: 'ON_GOOGLE',
    ON_GOOGLE_SUCCESS: 'ON_GOOGLE_SUCCESS',
    ON_GOOGLE_ERROR: 'ON_GOOGLE_ERROR',

    ON_EDIT_PROFILE: 'ON_EDIT_PROFILE',
    ON_EDIT_PROFILE_SUCCESS: 'ON_EDIT_PROFILE_SUCCESS',
    ON_EDIT_PROFILE_ERROR: 'ON_EDIT_PROFILE_ERROR',

}