export default {

    ON_FETCH_DATA_API: 'ON_FETCH_DATA_API',
    ON_FETCH_DATA_API_SUCCESS: 'ON_FETCH_DATA_API_SUCCESS',
    ON_FETCH_DATA_API_ERROR: 'ON_FETCH_DATA_API_ERROR',

    ON_FETCH_CATEGORY: 'ON_FETCH_CATEGORY',
    ON_FETCH_CATEGORY_SUCCESS: 'ON_FETCH_CATEGORY_SUCCESS',
    ON_FETCH_CATEGORY_ERROR: 'ON_FETCH_CATEGORY_ERROR',

    ON_FETCH_CURRENCY: 'ON_FETCH_CURRENCY',
    ON_FETCH_CURRENCY_SUCCESS: 'ON_FETCH_CURRENCY_SUCCESS',
    ON_FETCH_CURRENCY_ERROR: 'ON_FETCH_CURRENCY_ERROR',

    ON_SELECTED_CURRENCY: 'ON_SELECTED_CURRENCY',
    ON_SELECTED_CURRENCY_SUCCESS: 'ON_SELECTED_CURRENCY_SUCCESS',
}