require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'ExpenseTracker' do
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'RNFBAuth', :path => '../node_modules/@react-native-firebase/auth'
  pod 'RNFBFirestore', :path => '../node_modules/@react-native-firebase/firestore'
  pod 'GoogleSignIn', '~> 5.0.2'
  
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'ExpenseTrackerTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    system("sed -i '' '/s.resources/d' ../node_modules/react-native-vector-icons/RNVectorIcons.podspec")
    flipper_post_install(installer)
    end
  end

  # pod 'GoogleSignIn', '~> 5.0.0' // RNGoogleSignin requires GoogleSignIn >= 5.0.0
  
  target 'ExpenseTracker-tvOS' do
    # Pods for ExpenseTracker-tvOS
  
    target 'ExpenseTracker-tvOSTests' do
      inherit! :search_paths
      # Pods for testing
    end
  end
